// Static reference data used across the app.

// Default categories, seeded into Firestore's "categories" collection via
// the admin "Load default data" button. After seeding, categories are
// managed from /admin/categories — this array is only the starting set.
export const SEED_CATEGORIES = [
  { label: "Earbuds" },
  { label: "Smart Watches" },
  { label: "Speakers" },
  { label: "Power Banks" },
  { label: "Chargers" },
  { label: "Cables" },
  { label: "Phone Accessories" },
  { label: "Gadgets" },
];

// Bangladesh District -> Upazila/Thana
export const BD_DISTRICTS = {
  "ঢাকা": [
    "ধামরাই",
    "দোহার",
    "কেরাণীগঞ্জ",
    "নবাবগঞ্জ",
    "সাভার",
  ],

  "ফরিদপুর": [
    "আলফাডাঙ্গা",
    "ভাঙ্গা",
    "বোয়ালমারী",
    "চরভদ্রাসন",
    "ফরিদপুর সদর",
    "মধুখালী",
    "নগরকান্দা",
    "সদরপুর",
    "সালথা",
  ],

  "গাজীপুর": [
    "গাজীপুর সদর",
    "কালিয়াকৈর",
    "কালীগঞ্জ",
    "কাপাসিয়া",
    "শ্রীপুর",
  ],

  "গোপালগঞ্জ": [
    "গোপালগঞ্জ সদর",
    "কাশিয়ানী",
    "কোটালীপাড়া",
    "মুকসুদপুর",
    "টুঙ্গিপাড়া",
  ],

  "কিশোরগঞ্জ": [
    "অষ্টগ্রাম",
    "বাজিতপুর",
    "ভৈরব",
    "হোসেনপুর",
    "ইটনা",
    "করিমগঞ্জ",
    "কটিয়াদী",
    "কিশোরগঞ্জ সদর",
    "কুলিয়ারচর",
    "মিঠামইন",
    "নিকলী",
    "পাকুন্দিয়া",
    "তাড়াইল",
  ],

  "মাদারীপুর": [
    "কালকিনি",
    "মাদারীপুর সদর",
    "রাজৈর",
    "শিবচর",
    "ডাসার",
  ],

  "মানিকগঞ্জ": [
    "দৌলতপুর",
    "ঘিওর",
    "হরিরামপুর",
    "মানিকগঞ্জ সদর",
    "সাটুরিয়া",
    "শিবালয়",
    "সিংগাইর",
  ],

  "মুন্সীগঞ্জ": [
    "গজারিয়া",
    "লৌহজং",
    "মুন্সীগঞ্জ সদর",
    "সিরাজদিখান",
    "শ্রীনগর",
    "টংগিবাড়ী",
  ],

  "নারায়ণগঞ্জ": [
    "আড়াইহাজার",
    "সোনারগাঁ",
    "নারায়ণগঞ্জ সদর",
    "রূপগঞ্জ",
    "বন্দর",
  ],

  "নরসিংদী": [
    "বেলাবো",
    "মনোহরদী",
    "নরসিংদী সদর",
    "পলাশ",
    "রায়পুরা",
    "শিবপুর",
  ],

  "রাজবাড়ী": [
    "বালিয়াকান্দি",
    "গোয়ালন্দ",
    "কালুখালী",
    "পাংশা",
    "রাজবাড়ী সদর",
  ],

  "শরীয়তপুর": [
    "ভেদরগঞ্জ",
    "ডামুড্যা",
    "গোসাইরহাট",
    "নড়িয়া",
    "শরিয়তপুর সদর",
    "জাজিরা",
  ],

  "টাঙ্গাইল": [
    "বাসাইল",
    "ভূঞাপুর",
    "দেলদুয়ার",
    "ধনবাড়ী",
    "ঘাটাইল",
    "গোপালপুর",
    "কালিহাতী",
    "মধুপুর",
    "মির্জাপুর",
    "নাগরপুর",
    "সখিপুর",
    "টাঙ্গাইল সদর",
  ],

  "বাগেরহাট": [
    "চিতলমারী",
    "ফকিরহাট",
    "কচুয়া",
    "মোল্লাহাট",
    "মোংলা",
    "মোরেলগঞ্জ",
    "রামপাল",
    "শরণখোলা",
    "বাগেরহাট সদর",
  ],

  "চুয়াডাঙ্গা": [
    "আলমডাঙ্গা",
    "চুয়াডাঙ্গা সদর",
    "দামুড়হুদা",
    "জীবননগর",
  ],

  "যশোর": [
    "অভয়নগর",
    "বাঘারপাড়া",
    "চৌগাছা",
    "ঝিকরগাছা",
    "কেশবপুর",
    "যশোর সদর",
    "মণিরামপুর",
    "শার্শা",
  ],

  "ঝিনাইদহ": [
    "হরিণাকুন্ডু",
    "ঝিনাইদহ সদর",
    "কালীগঞ্জ",
    "কোটচাঁদপুর",
    "মহেশপুর",
    "শৈলকুপা",
  ],

  "খুলনা": [
    "বটিয়াঘাটা",
    "দাকোপ",
    "ডুমুরিয়া",
    "কয়রা",
    "পাইকগাছা",
    "ফুলতলা",
    "রূপসা",
    "তেরখাদা",
    "দিঘলিয়া",
  ],

  "কুষ্টিয়া": [
    "ভেড়ামারা",
    "দৌলতপুর",
    "খোকসা",
    "কুমারখালী",
    "কুষ্টিয়া সদর",
    "মিরপুর",
  ],

  "মাগুরা": [
    "মাগুরা সদর",
    "মহম্মদপুর",
    "শালিখা",
    "শ্রীপুর",
  ],

  "মেহেরপুর": [
    "গাংনী",
    "মুজিবনগর",
    "মেহেরপুর সদর",
  ],

  "নড়াইল": [
    "কালিয়া",
    "লোহাগড়া",
    "নড়াইল সদর",
  ],

  "সাতক্ষীরা": [
    "আশাশুনি",
    "দেবহাটা",
    "কলারোয়া",
    "কালিগঞ্জ",
    "সাতক্ষীরা সদর",
    "শ্যামনগর",
    "তালা",
  ],

  "বান্দরবান": [
    "আলীকদম",
    "বান্দরবান সদর",
    "লামা",
    "নাইক্ষ্যংছড়ি",
    "রোয়াংছড়ি",
    "রুমা",
    "থানচি",
  ],

  "ব্রাহ্মণবাড়িয়া": [
    "আখাউড়া",
    "বাঞ্ছারামপুর",
    "বিজয়নগর",
    "ব্রাহ্মণবাড়িয়া সদর",
    "আশুগঞ্জ",
    "কসবা",
    "নবীনগর",
    "নাসিরনগর",
    "সরাইল",
  ],

  "চাঁদপুর": [
    "চাঁদপুর সদর",
    "ফরিদগঞ্জ",
    "হাইমচর",
    "হাজীগঞ্জ",
    "কচুয়া",
    "মতলব দক্ষিণ",
    "মতলব উত্তর",
    "শাহরাস্তি",
  ],

  "চট্টগ্রাম": [
    "আনোয়ারা",
    "বাঁশখালী",
    "বোয়ালখালী",
    "চন্দনাইশ",
    "ফটিকছড়ি",
    "হাটহাজারী",
    "লোহাগাড়া",
    "মীরসরাই",
    "পটিয়া",
    "রাঙ্গুনিয়া",
    "রাউজান",
    "সন্দ্বীপ",
    "সাতকানিয়া",
    "সীতাকুন্ড",
    "কর্ণফুলী",
  ],

  "কুমিল্লা": [
    "বরুড়া",
    "ব্রাহ্মণপাড়া",
    "বুড়িচং",
    "চান্দিনা",
    "চৌদ্দগ্রাম",
    "সদর দক্ষিণ",
    "আদর্শ সদর",
    "দাউদকান্দি",
    "দেবিদ্বার",
    "হোমনা",
    "লাকসাম",
    "মনোহরগঞ্জ",
    "মেঘনা",
    "মুরাদনগর",
    "নাঙ্গলকোট",
    "তিতাস",
    "লালমাই",
  ],

  "কক্সবাজার": [
    "চকরিয়া",
    "কক্সবাজার সদর",
    "কুতুবদিয়া",
    "মহেশখালী",
    "পেকুয়া",
    "রামু",
    "টেকনাফ",
    "উখিয়া",
    "ঈদগাঁও",
  ],

  "ফেনী": [
    "ছাগলনাইয়া",
    "দাগনভূঞা",
    "ফেনী সদর",
    "ফুলগাজী",
    "পরশুরাম",
    "সোনাগাজী",
  ],

  "খাগড়াছড়ি": [
    "দীঘিনালা",
    "মানিকছড়ি",
    "খাগড়াছড়ি সদর",
    "লক্ষীছড়ি",
    "মহালছড়ি",
    "মাটিরাঙ্গা",
    "পানছড়ি",
    "রামগড়",
    "গুইমারা",
  ],

  "লক্ষ্মীপুর": [
    "কমলনগর",
    "লক্ষ্মীপুর সদর",
    "রায়পুর",
    "রামগঞ্জ",
    "রামগতি",
    "চন্দ্রগঞ্জ",
  ],

  "নোয়াখালী": [
    "বেগমগঞ্জ",
    "চাটখিল",
    "কোম্পানীগঞ্জ",
    "হাতিয়া",
    "সেনবাগ",
    "সোনাইমুড়ী",
    "সুবর্ণচর",
    "নোয়াখালী সদর",
    "কবিরহাট",
  ],

  "রাঙ্গামাটি": [
    "বাঘাইছড়ি",
    "বরকল",
    "কাউখালী",
    "কাপ্তাই",
    "জুরাছড়ি",
    "লংগদু",
    "নানিয়ারচর",
    "রাঙ্গামাটি সদর",
    "রাজস্থলী",
    "বিলাইছড়ি",
  ],

  "বগুড়া": [
    "আদমদিঘি",
    "বগুড়া সদর",
    "ধুনট",
    "দুপচাচিঁয়া",
    "গাবতলী",
    "কাহালু",
    "নন্দিগ্রাম",
    "সারিয়াকান্দি",
    "শাজাহানপুর",
    "শেরপুর",
    "শিবগঞ্জ",
    "সোনাতলা",
  ],

  "জয়পুরহাট": [
    "আক্কেলপুর",
    "জয়পুরহাট সদর",
    "কালাই",
    "পাঁচবিবি",
    "ক্ষেতলাল",
  ],

  "নওগাঁ": [
    "আত্রাই",
    "ধামইরহাট",
    "মান্দা",
    "মহাদেবপুর",
    "নওগাঁ সদর",
    "নিয়ামতপুর",
    "পত্নীতলা",
    "রাণীনগর",
    "সাপাহার",
    "বদলগাছী",
    "পোরশা",
  ],

  "নাটোর": [
    "বাগাতিপাড়া",
    "বড়াইগ্রাম",
    "গুরুদাসপুর",
    "লালপুর",
    "নাটোর সদর",
    "সিংড়া",
    "নলডাঙ্গা",
  ],

  "চাঁপাইনবাবগঞ্জ": [
    "শিবগঞ্জ",
    "ভোলাহাট",
    "গোমস্তাপুর",
    "নাচোল",
    "চাঁপাইনবাবগঞ্জ সদর",
  ],

  "পাবনা": [
    "আটঘরিয়া",
    "বেড়া",
    "ভাঙ্গুড়া",
    "চাটমোহর",
    "ফরিদপুর",
    "ঈশ্বরদী",
    "পাবনা সদর",
    "সাঁথিয়া",
    "সুজানগর",
  ],

  "রাজশাহী": [
    "বাঘা",
    "বাগমারা",
    "চারঘাট",
    "দুর্গাপুর",
    "গোদাগাড়ী",
    "মোহনপুর",
    "পবা",
    "পুঠিয়া",
    "তানোর",
  ],

  "সিরাজগঞ্জ": [
    "বেলকুচি",
    "চৌহালি",
    "কামারখন্দ",
    "কাজীপুর",
    "রায়গঞ্জ",
    "শাহজাদপুর",
    "সিরাজগঞ্জ সদর",
    "তাড়াশ",
    "উল্লাপাড়া",
  ],

  "হবিগঞ্জ": [
    "আজমিরীগঞ্জ",
    "বাহুবল",
    "বানিয়াচং",
    "চুনারুঘাট",
    "হবিগঞ্জ সদর",
    "লাখাই",
    "মাধবপুর",
    "নবীগঞ্জ",
    "শায়েস্তাগঞ্জ",
  ],

  "মৌলভীবাজার": [
    "বড়লেখা",
    "জুড়ী",
    "কমলগঞ্জ",
    "কুলাউড়া",
    "মৌলভীবাজার সদর",
    "রাজনগর",
    "শ্রীমঙ্গল",
  ],

  "সুনামগঞ্জ": [
    "বিশ্বম্ভরপুর",
    "ছাতক",
    "দিরাই",
    "ধর্মপাশা",
    "দোয়ারাবাজার",
    "জগন্নাথপুর",
    "জামালগঞ্জ",
    "শাল্লা",
    "সুনামগঞ্জ সদর",
    "তাহিরপুর",
    "শান্তিগঞ্জ",
    "মধ্যনগর",
  ],

  "সিলেট": [
    "বালাগঞ্জ",
    "বিয়ানীবাজার",
    "বিশ্বনাথ",
    "কোম্পানীগঞ্জ",
    "দক্ষিণ সুরমা",
    "ফেঞ্চুগঞ্জ",
    "গোলাপগঞ্জ",
    "গোয়াইনঘাট",
    "জৈন্তাপুর",
    "কানাইঘাট",
    "সিলেট সদর",
    "জকিগঞ্জ",
    "ওসমানী নগর",
  ],

  "দিনাজপুর": [
    "বিরামপুর",
    "বীরগঞ্জ",
    "বিরল",
    "বোচাগঞ্জ",
    "চিরিরবন্দর",
    "ফুলবাড়ী",
    "ঘোড়াঘাট",
    "হাকিমপুর",
    "কাহারোল",
    "খানসামা",
    "নবাবগঞ্জ",
    "পার্বতীপুর",
    "দিনাজপুর সদর",
  ],

  "গাইবান্ধা": [
    "ফুলছড়ি",
    "গাইবান্ধা সদর",
    "গোবিন্দগঞ্জ",
    "পলাশবাড়ী",
    "সাদুল্লাপুর",
    "সাঘাটা",
    "সুন্দরগঞ্জ",
  ],

  "কুড়িগ্রাম": [
    "ফুলবাড়ী",
    "ভূরুঙ্গামারী",
    "চর রাজিবপুর",
    "চিলমারী",
    "কুড়িগ্রাম সদর",
    "নাগেশ্বরী",
    "রাজারহাট",
    "রৌমারী",
    "উলিপুর",
  ],

  "লালমনিরহাট": [
    "আদিতমারী",
    "হাতীবান্ধা",
    "কালীগঞ্জ",
    "লালমনিরহাট সদর",
    "পাটগ্রাম",
  ],

  "নীলফামারী": [
    "ডোমার",
    "জলঢাকা",
    "কিশোরগঞ্জ",
    "নীলফামারী সদর",
    "সৈয়দপুর",
    "ডিমলা",
  ],

  "পঞ্চগড়": [
    "আটোয়ারী",
    "বোদা",
    "দেবীগঞ্জ",
    "পঞ্চগড় সদর",
    "তেঁতুলিয়া",
  ],

  "রংপুর": [
    "বদরগঞ্জ",
    "কাউনিয়া",
    "রংপুর সদর",
    "মিঠাপুকুর",
    "পীরগাছা",
    "পীরগঞ্জ",
    "তারাগঞ্জ",
    "গংগাচড়া",
  ],

  "ঠাকুরগাঁও": [
    "পীরগঞ্জ",
    "বালিয়াডাঙ্গী",
    "হরিপুর",
    "রাণীশংকৈল",
    "ঠাকুরগাঁও সদর",
    "ভূল্লী",
    "রুহিয়া",
  ],

  "জামালপুর": [
    "বকশীগঞ্জ",
    "দেওয়ানগঞ্জ",
    "ইসলামপুর",
    "জামালপুর সদর",
    "মাদারগঞ্জ",
    "মেলান্দহ",
    "সরিষাবাড়ী",
  ],

  "ময়মনসিংহ": [
    "ভালুকা",
    "ধোবাউড়া",
    "ফুলবাড়ীয়া",
    "গফরগাঁও",
    "গৌরীপুর",
    "হালুয়াঘাট",
    "ঈশ্বরগঞ্জ",
    "ময়মনসিংহ সদর",
    "মুক্তাগাছা",
    "নান্দাইল",
    "ফুলপুর",
    "তারাকান্দা",
    "ত্রিশাল",
  ],

  "নেত্রকোণা": [
    "আটপাড়া",
    "বারহাট্টা",
    "দুর্গাপুর",
    "খালিয়াজুরী",
    "কলমাকান্দা",
    "কেন্দুয়া",
    "মদন",
    "মোহনগঞ্জ",
    "নেত্রকোণা সদর",
    "পূর্বধলা",
  ],

  "শেরপুর": [
    "ঝিনাইগাতী",
    "নকলা",
    "নালিতাবাড়ী",
    "শেরপুর সদর",
    "শ্রীবরদী",
  ],

  "বরগুনা": [
    "আমতলী",
    "বামনা",
    "বরগুনা সদর",
    "বেতাগী",
    "পাথরঘাটা",
    "তালতলী",
  ],

  "বরিশাল": [
    "আগৈলঝাড়া",
    "বাবুগঞ্জ",
    "বাকেরগঞ্জ",
    "বানারীপাড়া",
    "গৌরনদী",
    "হিজলা",
    "বরিশাল সদর",
    "মেহেন্দিগঞ্জ",
    "মুলাদী",
    "উজিরপুর",
  ],

  "ভোলা": [
    "ভোলা সদর",
    "বোরহানউদ্দিন",
    "দৌলতখান",
    "লালমোহন",
    "মনপুরা",
    "তজুমদ্দিন",
    "চরফ্যাশন",
  ],

  "ঝালকাঠি": [
    "ঝালকাঠি সদর",
    "নলছিটি",
    "কাঠালিয়া",
    "রাজাপুর",
  ],

  "পটুয়াখালী": [
    "বাউফল",
    "দশমিনা",
    "দুমকী",
    "কলাপাড়া",
    "মির্জাগঞ্জ",
    "পটুয়াখালী সদর",
    "রাঙ্গাবালী",
    "গলাচিপা",
  ],

  "পিরোজপুর": [
    "ভান্ডারিয়া",
    "কাউখালী",
    "মঠবাড়ীয়া",
    "নাজিরপুর",
    "পিরোজপুর সদর",
    "নেছারাবাদ",
    "জিয়ানগর",
  ],
};

// Seed data — pushed to Firestore once via the "Load default data" button
// in /admin, so the store looks complete on first load. After seeding, all
// product data lives in Firestore and is managed from /admin.
export const SEED_PRODUCTS = [
  {
    name: "Aria Pro Wireless Earbuds",
    slug: "aria-pro-wireless-earbuds",
    price: 3490,
    discountPrice: 2990,
    description:
      "Active noise cancelling earbuds with a 32-hour total battery life, IPX5 sweat resistance, and a pocket-sized charging case finished in soft-touch matte plastic.",
    images: ["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=1000&q=80"],
    stock: 24,
    category: "earbuds",
    featured: true,
    trending: true,
    available: true,
  },
  {
    name: "Pulse Fit Smart Watch",
    slug: "pulse-fit-smart-watch",
    price: 4990,
    discountPrice: 3990,
    description:
      "A 1.4-inch AMOLED smart watch with heart-rate and SpO2 tracking, 7-day battery life, and 100+ workout modes. Compatible with Android and iOS.",
    images: ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=1000&q=80"],
    stock: 18,
    category: "smart-watches",
    featured: true,
    trending: true,
    available: true,
  },
  {
    name: "Orbit Mini Bluetooth Speaker",
    slug: "orbit-mini-bluetooth-speaker",
    price: 1990,
    discountPrice: null,
    description:
      "A palm-sized speaker with surprisingly deep bass, 12-hour playtime, and IPX6 water resistance — built for the beach, the shower, and everywhere in between.",
    images: ["https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=1000&q=80"],
    stock: 30,
    category: "speakers",
    featured: true,
    trending: false,
    available: true,
  },
  {
    name: "Voyage 20000mAh Power Bank",
    slug: "voyage-20000mah-power-bank",
    price: 2490,
    discountPrice: 2190,
    description:
      "20000mAh high-capacity power bank with 22.5W fast charging and dual USB output — enough to charge a phone five times over.",
    images: ["https://images.unsplash.com/photo-1609592806955-d69355f60c1e?w=1000&q=80"],
    stock: 40,
    category: "power-banks",
    featured: false,
    trending: true,
    available: true,
  },
  {
    name: "Volt 30W Fast Charger",
    slug: "volt-30w-fast-charger",
    price: 990,
    discountPrice: null,
    description:
      "A compact 30W GaN charger that fits in your pocket, with intelligent power delivery for phones, tablets, and laptops.",
    images: ["https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=1000&q=80"],
    stock: 50,
    category: "chargers",
    featured: false,
    trending: false,
    available: true,
  },
  {
    name: "Weave Braided USB-C Cable (1.2m)",
    slug: "weave-braided-usb-c-cable",
    price: 490,
    discountPrice: null,
    description:
      "A durable nylon-braided USB-C cable rated for 20,000+ bends, supporting fast charging and data transfer.",
    images: ["https://images.unsplash.com/photo-1621330396173-e41b1cafd17f?w=1000&q=80"],
    stock: 80,
    category: "cables",
    featured: false,
    trending: false,
    available: true,
  },
  {
    name: "Halo MagSafe Wallet Stand",
    slug: "halo-magsafe-wallet-stand",
    price: 1290,
    discountPrice: 990,
    description:
      "A magnetic leather card holder that snaps onto the back of your phone and folds out into a kickstand.",
    images: ["https://images.unsplash.com/photo-1601593346740-925612772716?w=1000&q=80"],
    stock: 35,
    category: "phone-accessories",
    featured: true,
    trending: false,
    available: true,
  },
  {
    name: "Clip-On Ring Light Mini",
    slug: "clip-on-ring-light-mini",
    price: 890,
    discountPrice: null,
    description:
      "A rechargeable 3-inch clip-on ring light with 3 brightness modes — perfect for video calls and content on the go.",
    images: ["https://images.unsplash.com/photo-1616423641454-6ba86b8b8dfc?w=1000&q=80"],
    stock: 22,
    category: "gadgets",
    featured: false,
    trending: true,
    available: true,
  },
  {
    name: "Anchor Phone Mount for Car",
    slug: "anchor-phone-mount-for-car",
    price: 790,
    discountPrice: null,
    description:
      "A one-hand, spring-loaded car vent mount that holds any phone securely on rough roads.",
    images: ["https://images.unsplash.com/photo-1512428813834-c702c7702b78?w=1000&q=80"],
    stock: 28,
    category: "phone-accessories",
    featured: false,
    trending: false,
    available: true,
  },
  {
    name: "Nimbus Noise-Isolating Headphones",
    slug: "nimbus-noise-isolating-headphones",
    price: 3290,
    discountPrice: 2790,
    description:
      "Over-ear headphones with plush memory-foam cushions, 40-hour battery life, and a folding design for travel.",
    images: ["https://images.unsplash.com/photo-1583394838336-acd977736f90?w=1000&q=80"],
    stock: 15,
    category: "earbuds",
    featured: false,
    trending: false,
    available: true,
  },
  {
    name: "Flux 4-Port USB Hub",
    slug: "flux-4-port-usb-hub",
    price: 690,
    discountPrice: null,
    description:
      "A slim aluminium 4-port USB 3.0 hub that turns one port into four — ideal for laptops with limited connectivity.",
    images: ["https://images.unsplash.com/photo-1625948515291-69613efd103f?w=1000&q=80"],
    stock: 33,
    category: "gadgets",
    featured: false,
    trending: false,
    available: true,
  },
  {
    name: "Aster Kids Smart Watch",
    slug: "aster-kids-smart-watch",
    price: 2290,
    discountPrice: 1890,
    description:
      "A durable, colourful smart watch for kids with step tracking, games, and a 2-day battery — no app or SIM required.",
    images: ["https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=1000&q=80"],
    stock: 20,
    category: "smart-watches",
    featured: false,
    trending: false,
    available: true,
  },
];

export const DEFAULT_SETTINGS = {
  storeName: "KabbirMart",
  storePhone: "+880 1XXX-XXXXXX",
  storeEmail: "hello@kabbirmart.com",
  storeAddress: "Bogra, Rajshahi Division, Bangladesh",
  deliveryCharge: 70,
  deliveryChargeDhaka: 60,
  codCharge: 0,
};

export const DEFAULT_HOMEPAGE = {
  heroTitle: "Everyday tech, made to feel considered.",
  heroSubtitle:
    "Earbuds, watches, speakers and small useful gadgets — chosen for how they work, and how they look on your desk.",
  heroImage: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=1400&q=80",
  heroButtonText: "Shop the collection",
  heroButtonLink: "/#featured",
  promoTitle: "Cash on Delivery, everywhere in Bangladesh",
  promoText:
    "Order without a card. Pay in cash when your package arrives at your door — no account, no hassle.",
  promoImage: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=1400&q=80",
};
